import type {
  Id,
  Project,
  Requirement,
  RequirementStatus,
  ResourceRef,
  Task,
  TaskStatus,
  Workspace,
} from '@baton/shared'

// Create inputs omit id and timestamps: id is generated by the Store, timestamps maintained by the DB.
export type WorkspaceCreate = { name: string }
export type ProjectCreate = { workspaceId: Id; name: string; description?: string }
export type RequirementCreate = {
  projectId: Id
  title: string
  description?: string
  resources?: ResourceRef[]
  tags?: string[]
  status?: RequirementStatus
}
export type RequirementPatch = Partial<{
  title: string
  description: string
  resources: ResourceRef[]
  tags: string[]
  status: RequirementStatus
}>
export type TaskCreate = {
  requirementId: Id
  title: string
  spec?: string
  requires?: string[]
  dependsOn?: Id[]
  status?: TaskStatus
}
export type TaskPatch = Partial<{
  title: string
  spec: string
  requires: string[]
  dependsOn: Id[]
  status: TaskStatus
}>

export type RequirementWithTasks = { requirement: Requirement; tasks: Task[] }

// Persistence port: fully async, leaving room to swap to a networked DB later. First impl: PrismaStore.
export type Store = {
  workspaces: {
    create(input: WorkspaceCreate): Promise<Workspace>
    get(id: Id): Promise<Workspace | null>
    list(): Promise<Workspace[]>
    delete(id: Id): Promise<void>
  }
  projects: {
    create(input: ProjectCreate): Promise<Project>
    get(id: Id): Promise<Project | null>
    listByWorkspace(workspaceId: Id): Promise<Project[]>
    delete(id: Id): Promise<void>
  }
  requirements: {
    create(input: RequirementCreate): Promise<Requirement>
    get(id: Id): Promise<Requirement | null>
    listByProject(projectId: Id): Promise<Requirement[]>
    update(id: Id, patch: RequirementPatch): Promise<Requirement>
    delete(id: Id): Promise<void>
  }
  tasks: {
    create(input: TaskCreate): Promise<Task>
    get(id: Id): Promise<Task | null>
    listByRequirement(requirementId: Id): Promise<Task[]>
    update(id: Id, patch: TaskPatch): Promise<Task>
    delete(id: Id): Promise<void>
  }
  getRequirementWithTasks(id: Id): Promise<RequirementWithTasks | null>
  close(): Promise<void>
}
