import type {
  AgentKind,
  Code,
  Id,
  Project,
  Requirement,
  RequirementStatus,
  ResourceRef,
  Session,
  SessionEvent,
  SessionEventType,
  SessionMode,
  Task,
  TaskComment,
  TaskStatus,
  User,
  Worker,
  Workspace,
} from '@baton/shared'

// Server-internal: the public User view plus the password hash (never serialized
// to clients). The store works in UserRecord; routes strip it down to User.
export type UserRecord = User & { passwordHash: string }
export type UserCreate = { username: string; passwordHash: string }

// Create inputs omit id/code/timestamps: id is generated by the DB (autoincrement);
// code is assigned by the Store via CodeCounter; timestamps maintained by Prisma.
export type WorkspaceCreate = { name: string }
export type WorkspacePatch = Partial<{ name: string }>
export type ProjectCreate = { workspaceId: Id; name: string; description?: string }
export type ProjectPatch = Partial<{ name: string; description: string }>
export type RequirementCreate = {
  projectId: Id
  title: string
  description?: string
  body?: string
  resources?: ResourceRef[]
  status?: RequirementStatus
}
export type RequirementPatch = Partial<{
  title: string
  description: string
  body: string
  resources: ResourceRef[]
  status: RequirementStatus
}>
export type TaskCreate = {
  requirementId: Id
  title: string
  body?: string
  dependsOn?: Id[]
  status?: TaskStatus
}
export type TaskPatch = Partial<{
  title: string
  body: string
  dependsOn: Id[]
  status: TaskStatus
}>
// Comments are append-only — created one at a time, never updated. No patch type.
export type TaskCommentCreate = { taskId: Id; body: string; workerId?: Id }

export type RequirementWithTasks = { requirement: Requirement; tasks: Task[] }

// Session creation: just the collaboration-dimension metadata. workerId is
// required (Session → Worker FK, onDelete Cascade). agentSessionId + worktreePath
// are filled later by the owning Worker via `materialize`.
export type SessionCreate = {
  projectId: Id
  workerId: Id
  mode: SessionMode
  name: string
  agentKind: AgentKind
}
// Worker-supplied materialization: the agent session id it minted + the git
// worktree it created for this session's cwd.
export type SessionMaterialize = {
  agentSessionId: string
  worktreePath: string
}

// Worker register — idempotent by (projectId, machineId) first, then
// (projectId, name). See app.ts for the full priority algorithm. apiToken is
// issued at creation and returned on every successful (re)register.
export type WorkerRegister = {
  projectId: Id
  machineId: string
  name: string
  hostname: string
}
export type WorkerRegisterOutcome =
  | { kind: 'created'; worker: Worker; apiToken: string }
  | { kind: 'reattached-machine'; worker: Worker; apiToken: string } // rule 1: same machineId
  | { kind: 'claimed-legacy'; worker: Worker; apiToken: string } //     rule 2b: filled machineId
  | { kind: 'name-collision'; existing: Worker } //                     rule 2c: name in use

// Persistence port: fully async, leaving room to swap to a networked DB later. First impl: PrismaStore.
export type Store = {
  workspaces: {
    create(input: WorkspaceCreate): Promise<Workspace>
    get(id: Id): Promise<Workspace | null>
    list(): Promise<Workspace[]>
    update(id: Id, patch: WorkspacePatch): Promise<Workspace>
    delete(id: Id): Promise<void>
  }
  projects: {
    create(input: ProjectCreate): Promise<Project>
    get(id: Id): Promise<Project | null>
    listByWorkspace(workspaceId: Id): Promise<Project[]>
    update(id: Id, patch: ProjectPatch): Promise<Project>
    delete(id: Id): Promise<void>
  }
  requirements: {
    create(input: RequirementCreate): Promise<Requirement>
    get(id: Id): Promise<Requirement | null>
    getByCode(projectId: Id, code: Code): Promise<Requirement | null>
    listByProject(projectId: Id): Promise<Requirement[]>
    update(id: Id, patch: RequirementPatch): Promise<Requirement>
    delete(id: Id): Promise<void>
  }
  tasks: {
    create(input: TaskCreate): Promise<Task>
    get(id: Id): Promise<Task | null>
    getByCode(projectId: Id, code: Code): Promise<Task | null>
    listByRequirement(requirementId: Id): Promise<Task[]>
    update(id: Id, patch: TaskPatch): Promise<Task>
    delete(id: Id): Promise<void>
  }
  // Append-only collaboration log on a Task. Create = single INSERT; list in
  // insertion order. No update/delete (cascades away with its Task).
  taskComments: {
    create(input: TaskCommentCreate): Promise<TaskComment>
    listByTask(taskId: Id): Promise<TaskComment[]>
  }
  sessions: {
    create(input: SessionCreate): Promise<Session>
    materialize(id: Id, input: SessionMaterialize): Promise<Session>
    // Human rename — sets name + locks it against auto-title.
    rename(id: Id, name: string): Promise<Session>
    // Non-locking, guarded set (placeholder + auto-title). null when locked.
    autoTitle(id: Id, name: string): Promise<Session | null>
    get(id: Id): Promise<Session | null>
    getByShareToken(token: string): Promise<Session | null>
    listByProject(projectId: Id): Promise<Session[]>
    // DELETE the row. Irreversible. Transcript events cascade away with it (FK).
    destroy(id: Id): Promise<void>
    // Append-only transcript. appendEvent assigns the next per-session sequence;
    // listEvents returns the full history in order (for SSE replay).
    appendEvent(sessionId: Id, type: SessionEventType, payload: unknown): Promise<SessionEvent>
    listEvents(sessionId: Id): Promise<SessionEvent[]>
  }
  workers: {
    // Idempotent register following the rule 1 / 2a / 2b / 2c algorithm.
    register(input: WorkerRegister): Promise<WorkerRegisterOutcome>
    get(id: Id): Promise<Worker | null>
    getByToken(token: string): Promise<Worker | null>
    findByMachine(projectId: Id, machineId: string): Promise<Worker | null>
    listByProject(projectId: Id): Promise<Worker[]>
    // DELETE the row (cascade Session). Irreversible.
    destroy(id: Id): Promise<void>
  }
  // Back-office login users. Auth is enforced iff count() > 0 (see cookie gate);
  // `first` is the user a share-token login maps to (full access, one user in v0).
  users: {
    create(input: UserCreate): Promise<UserRecord>
    get(id: Id): Promise<UserRecord | null>
    getByUsername(username: string): Promise<UserRecord | null>
    first(): Promise<UserRecord | null>
    count(): Promise<number>
  }
  getRequirementWithTasks(id: Id): Promise<RequirementWithTasks | null>
  close(): Promise<void>
}
