import type {
  Assignment,
  AssignmentEvent,
  AssignmentStatus,
  Code,
  Id,
  Project,
  Requirement,
  RequirementStatus,
  ResourceRef,
  Session,
  SessionMode,
  SessionStatus,
  Task,
  TaskStatus,
  Workspace,
} from '@baton/shared'

// Create inputs omit id/code/timestamps: id is generated by the DB (autoincrement);
// code is assigned by the Store via CodeCounter; timestamps maintained by Prisma.
export type WorkspaceCreate = { name: string }
export type ProjectCreate = { workspaceId: Id; name: string; description?: string }
export type RequirementCreate = {
  projectId: Id
  title: string
  description?: string
  resources?: ResourceRef[]
  tags?: string[]
  status?: RequirementStatus
}
export type RequirementPatch = Partial<{
  title: string
  description: string
  resources: ResourceRef[]
  tags: string[]
  status: RequirementStatus
}>
export type TaskCreate = {
  requirementId: Id
  title: string
  spec?: string
  requires?: string[]
  dependsOn?: Id[]
  status?: TaskStatus
}
export type TaskPatch = Partial<{
  title: string
  spec: string
  requires: string[]
  dependsOn: Id[]
  status: TaskStatus
}>

export type RequirementWithTasks = { requirement: Requirement; tasks: Task[] }

// Session registration; apiToken is generated by the store and returned only once.
export type SessionRegister = {
  projectId: Id
  mode: SessionMode
  name: string
  capabilities?: string[]
}
export type SessionWithToken = Session & { apiToken: string }

export type AssignmentListFilter = { status?: AssignmentStatus[]; sessionId?: Id }

// A successful claim hands the worker both the bookkeeping record and the task to run.
export type ClaimResult = { assignment: Assignment; task: Task }

// Persistence port: fully async, leaving room to swap to a networked DB later. First impl: PrismaStore.
export type Store = {
  workspaces: {
    create(input: WorkspaceCreate): Promise<Workspace>
    get(id: Id): Promise<Workspace | null>
    list(): Promise<Workspace[]>
    delete(id: Id): Promise<void>
  }
  projects: {
    create(input: ProjectCreate): Promise<Project>
    get(id: Id): Promise<Project | null>
    listByWorkspace(workspaceId: Id): Promise<Project[]>
    delete(id: Id): Promise<void>
  }
  requirements: {
    create(input: RequirementCreate): Promise<Requirement>
    get(id: Id): Promise<Requirement | null>
    getByCode(projectId: Id, code: Code): Promise<Requirement | null>
    listByProject(projectId: Id): Promise<Requirement[]>
    update(id: Id, patch: RequirementPatch): Promise<Requirement>
    delete(id: Id): Promise<void>
  }
  tasks: {
    create(input: TaskCreate): Promise<Task>
    get(id: Id): Promise<Task | null>
    getByCode(projectId: Id, code: Code): Promise<Task | null>
    listByRequirement(requirementId: Id): Promise<Task[]>
    update(id: Id, patch: TaskPatch): Promise<Task>
    delete(id: Id): Promise<void>
  }
  sessions: {
    register(input: SessionRegister): Promise<SessionWithToken>
    get(id: Id): Promise<Session | null>
    getByCode(projectId: Id, code: Code): Promise<Session | null>
    getByToken(token: string): Promise<Session | null>
    listByProject(projectId: Id): Promise<Session[]>
    heartbeat(id: Id, status?: SessionStatus): Promise<Session>
    close(id: Id): Promise<void>
    claim(sessionId: Id): Promise<ClaimResult | null>
    sweepStale(now: number, idleThresholdMs: number): Promise<number>
  }
  assignments: {
    get(id: Id): Promise<Assignment | null>
    getByCode(projectId: Id, code: Code): Promise<Assignment | null>
    listByProject(projectId: Id, filter?: AssignmentListFilter): Promise<Assignment[]>
    appendEvent(id: Id, sequence: number, payload: unknown): Promise<AssignmentEvent>
    listEvents(id: Id): Promise<AssignmentEvent[]>
    complete(id: Id, status: 'done' | 'failed', result?: string): Promise<Assignment>
    abandon(id: Id, reason?: string): Promise<Assignment>
  }
  getRequirementWithTasks(id: Id): Promise<RequirementWithTasks | null>
  close(): Promise<void>
}
